name: deployment in Render

on:
  push:
    branches: [main]
    paths:
      - 'petstore-feature5-backend/**'
      - '.github/workflows/**'

  pull_request:
    branches: [main]
    paths:
      - 'petstore-feature5-backend/**'

env:
  JAVA_VERSION: '21'


jobs:
  avoid_redundancy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel redundant builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Install JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Check code style with Checkstyle
        run: mvn checkstyle:check
        continue-on-error: true

      - name: Run Maven Verify
        run: mvn verify -DskipTests

  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Prueba
        run: echo "Build"
  test:
    needs: [lint, build]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Install JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Run Tests
        run: echo "Should run mvn test"

      - name: Generate Test Coverage Report
        run: echo "Should run mvn jacoco:report"

      - name: Upload Test Results
        run: echo "Tests Results"

  e2e:
    needs: [lint, build]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Install JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Run E2E Tests
        run: echo "There's not tests yet"

      - name: Upload E2E Test Results
        run: echo "E2E Results"




