name: deployment in Render

on:
  push:
    branches: [main]
    paths:
      - 'petstore-feature5-backend/**'
      - '.github/workflows/**'

  pull_request:
    branches: [main]
    paths:
      - 'petstore-feature5-backend/**'

env:
  JAVA_VERSION: '21'
  WORKING_DIRECTORY: 'petstore-feature5-backend'


jobs:
  avoid_redundancy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel redundant builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

