name: deployment in Render

on:
  push:
    branches: [main]
    paths:
      - 'petstore-feature5-backend/**'
      - '.github/workflows/**'

  pull_request:
    branches: [main]
    paths:
      - 'petstore-feature5-backend/**'

env:
  JAVA_VERSION: '21'
  WORKING_DIRECTORY: 'petstore-feature5-backend/petstore-feature5-backend'

jobs:
  avoid_redundancy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel redundant builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  lint:
    name: Code Quality Check
    needs: avoid_redundancy
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
          cache-dependency-path: '${{ env.WORKING_DIRECTORY }}/pom.xml'

      - name: Check code style with Checkstyle
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: mvn checkstyle:check
        continue-on-error: true

      - name: Run Maven Verify
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: mvn verify -DskipTests

      - name: Upload Checkstyle Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-results
          path: ${{ env.WORKING_DIRECTORY }}/target/checkstyle-result.xml
        continue-on-error: true