name: Static Analysis - Java (Spring Boot, Maven)

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  static-analysis:
    name: Run Static Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle -Dmaven.test.skip=true --batch-mode

      - name: Run PMD
        run: mvn pmd:pmd -Dmaven.test.skip=true --batch-mode

      - name: Run SpotBugs
        run: mvn com.github.spotbugs:spotbugs-maven-plugin:4.8.3.0:spotbugs -Dmaven.test.skip=true --batch-mode

      - name: Upload Checkstyle reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-reports
          path: target/checkstyle-result.xml

      - name: Upload PMD reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pmd-reports
          path: target/pmd.xml

      - name: Upload SpotBugs reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-reports
          path: target/spotbugsXml.xml